# Checks spelling issues in the repo
name: SpellCheck

on: workflow_call

permissions:
  contents: read

jobs:
  analyze:
    name: Run spell check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Run a spell check
      uses: crate-ci/typos@b63f421581dce830bda2f597a678cb7776b41877 # v1.18.2
      with:
        config: ./.github/workflows/.spellcheck-conf.toml
